openapi: 3.0.1
info:
  title: TestGit
  description: API Definition of TestGit
  version: 1.0.0
servers:
- url: http://localhost:8290/testGit
paths:
  /:
    get:
      responses:
        default:
          description: Default response
